### ISSUE TITLE
CrossWire

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/upptime-sword-repos#1]
Use CamelCase for CrossWire please.

**Comment by timbze** [comment]
Done.

Interesting how you find this repo :)

This was more of a test, but thought it might be nice to have. CrossWire could host this on their own repo, if they wanted to.

Upptime has quite a few more features, including some types of notifications and the ability to automatically tag specific people to specific sites when they are down. (Upptime creates an issue when a site is down)
